version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: you@example.com
    volumes_from:
      - nginx-proxy
  # whoami:
  #   image: jwilder/whoami
  #   container_name: whoami
  #   expose:
  #       - "8000"
  #   environment:
  #       - VIRTUAL_HOST=example.com
  #       - VIRTUAL_PORT=8000
  #       - LETSENCRYPT_HOST=example.com
  #       - LETSENCRYPT_EMAIL=example@example.com
  #   network_mode: bridge
  #   networks:
  #       - nginx-proxy


networks:
  nginx-proxy:
    external: true

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
