version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    environment:
      DHPARAM_GENERATION: 'false'
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # acme-companion
      - html:/usr/share/nginx/html
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    networks:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy

volumes:
  certs:
    name: nginx-proxy-certs
  dhparam:
    name: nginx-proxy-dhparam
  vhost:
    name: nginx-proxy-vhost
  html:
    name: nginx-proxy-acme-companion-html
  acme:
    name: nginx-proxy-acme-companion-acme
